name: Scheduled Refresh

on:
  schedule:
    - '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Run Task
        run: node index.js

      - name: Commit Changes
        run: git add -A && git commit -m "Refresh Dataset [$(date '+%F %T %z')]" && git push

